const data = [
  {
    id: 1,
    title: "Televisions",
    slug: "televisions",
    img: "/images/categories/categories-01.png",
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-01-01"),
  },
  {
    id: 2,
    title: "Laptop & PC",
    slug: "computer",
    img: "/images/categories/categories-02.png",
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-01-01"),
  },
  {
    id: 3,
    title: "Mobile & Tablets",
    slug: "mobile",
    img: "/images/categories/categories-03.png",
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-01-01"),
  },
  {
    id: 4,
    title: "Games & Videos",
    slug: "electronics",
    img: "/images/categories/categories-04.png",
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-01-01"),
  },
  {
    id: 5,
    title: "Home Appliances",
    slug: "appliances",
    img: "/images/categories/categories-05.png",
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-01-01"),
  },
  {
    id: 6,
    title: "Health & Sports",
    slug: "sports",
    img: "/images/categories/categories-06.png",
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-01-01"),
  },
  {
    id: 7,
    title: "Watches",
    slug: "watch",
    img: "/images/categories/categories-07.png",
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-01-01"),
  },
  {
    id: 8,
    title: "Accessories",
    slug: "accessories",
    img: "/images/categories/categories-04.png",
    createdAt: new Date("2026-01-01"),
    updatedAt: new Date("2026-01-01"),
  },
];

export default data;
