/**
 * Demo catalogue for `prisma/seed.js --demo`.
 * Images are the product photos bundled in /public/images (nothing is downloaded).
 * Prices are in INR, tax-exclusive; compareAt is the struck-through list price.
 */
const P = (n, suffix = "bg-1") => `/images/products/product-${n}-${suffix}.png`;

const categories = [
  { name: "Televisions", slug: "televisions", img: "/images/categories/categories-01.png" },
  { name: "Computers & Accessories", slug: "computers-accessories", img: "/images/categories/categories-02.png" },
  { name: "Mobiles & Tablets", slug: "mobiles-tablets", img: "/images/categories/categories-03.png" },
  { name: "Gaming & Audio", slug: "gaming-audio", img: "/images/categories/categories-04.png" },
  { name: "Home Appliances", slug: "home-appliances", img: "/images/categories/categories-05.png" },
  { name: "Health & Fitness", slug: "health-fitness", img: "/images/categories/categories-06.png" },
  { name: "Wearables", slug: "wearables", img: "/images/categories/categories-07.png" },
];

const products = [
  {
    title: "43-inch 4K Smart LED TV",
    sku: "TV-43-4K",
    category: "televisions",
    price: 32990,
    compare: 39990,
    stock: 10,
    tax: 18,
    images: [P(10), P(10, "bg-2")],
    tags: "tv, 4k, smart tv, television",
    short: "Crisp 4K picture, built-in streaming apps and voice remote.",
    description:
      "Bring the cinema home with a 43-inch 4K UHD display, HDR support and slim bezels. Built-in streaming apps, three HDMI ports and a voice-enabled remote make it ready to use out of the box.",
    specs: [["Screen size", "43 inch"], ["Resolution", "3840 x 2160 (4K UHD)"], ["Connectivity", "3x HDMI, 2x USB, Wi-Fi, Bluetooth"], ["Warranty", "1 year"]],
  },
  {
    title: "13-inch Ultra-Thin Laptop 8GB/256GB",
    sku: "LAP-13-8-256",
    category: "computers-accessories",
    price: 84990,
    compare: 94990,
    stock: 14,
    tax: 18,
    images: [P(4), P(4, "bg-2")],
    tags: "laptop, ultrabook, work, student",
    short: "Fanless, featherlight laptop with all-day battery life.",
    description:
      "A thin, silent laptop for work and study. The high-resolution display, fast SSD and efficient processor keep you productive from morning to evening on a single charge.",
    specs: [["Display", "13.6 inch Liquid Retina"], ["Memory / Storage", "8 GB / 256 GB SSD"], ["Battery", "Up to 15 hours"], ["Weight", "1.24 kg"]],
  },
  {
    title: "24-inch All-in-One Desktop",
    sku: "AIO-24-8-256",
    category: "computers-accessories",
    price: 119900,
    compare: 129900,
    stock: 8,
    tax: 18,
    images: [P(3), P(3, "bg-2")],
    tags: "desktop, all in one, office",
    short: "Space-saving desktop with a vivid 4.5K display.",
    description:
      "Everything you need in one slim unit: a bright 24-inch display, studio-quality mic array, 1080p camera and speakers. Clean desk, fewer cables.",
    specs: [["Display", "24 inch 4.5K"], ["Memory / Storage", "8 GB / 256 GB SSD"], ["Camera", "1080p FaceTime-style HD"], ["Warranty", "1 year"]],
  },
  {
    title: "Ergonomic Wireless Mouse",
    sku: "MOU-ERGO-GR",
    category: "computers-accessories",
    price: 7499,
    compare: 8999,
    stock: 80,
    tax: 18,
    images: [P(6), P(6, "bg-2")],
    tags: "mouse, wireless, ergonomic, office",
    short: "Sculpted for all-day comfort with a fast scroll wheel.",
    description:
      "A precision wireless mouse with a sculpted thumb rest, quiet clicks and a magnetic scroll wheel. Connects to up to three devices and charges over USB-C.",
    specs: [["Connectivity", "Bluetooth / USB receiver"], ["Battery", "Up to 70 days"], ["Buttons", "7 programmable"], ["Sensor", "8000 DPI"]],
  },
  {
    title: "Wi-Fi 6 Dual-Band Router AX3000",
    sku: "NET-AX3000",
    category: "computers-accessories",
    price: 12999,
    compare: 15999,
    stock: 19,
    tax: 18,
    images: [P(8)],
    tags: "router, wifi 6, networking, internet",
    short: "Fast, stable Wi-Fi 6 coverage for the whole home.",
    description:
      "Dual-band Wi-Fi 6 with four high-gain antennas and up to 3000 Mbps combined speed. Built-in network security and parental controls keep your connection safe.",
    specs: [["Standard", "Wi-Fi 6 (802.11ax)"], ["Speed", "574 Mbps (2.4 GHz) + 2402 Mbps (5 GHz)"], ["Ports", "1x WAN, 4x Gigabit LAN"], ["Antennas", "4 external"]],
  },
  {
    title: "Dual-Camera Smartphone 6GB",
    sku: "PHN-DC-6",
    category: "mobiles-tablets",
    price: 62999,
    compare: 69999,
    stock: 0, // stock is per variant below
    tax: 18,
    images: [P(2), P(2, "bg-2")],
    tags: "smartphone, mobile, 5g, camera",
    short: "Bright OLED display, dual 12MP cameras and all-day battery.",
    description:
      "A fast, reliable 5G smartphone with a vivid OLED display, dual 12MP cameras with low-light photo mode and a battery that lasts through the day. Choose your storage.",
    specs: [["Display", "6.7 inch OLED"], ["Camera", "Dual 12 MP"], ["Connectivity", "5G, Wi-Fi 6, Bluetooth 5.3"], ["Warranty", "1 year"]],
    variants: [
      { title: "128 GB", sku: "PHN-DC-6-128", price: 62999, stock: 15, attrs: { size: "128 GB" } },
      { title: "256 GB", sku: "PHN-DC-6-256", price: 72999, stock: 10, attrs: { size: "256 GB" } },
    ],
  },
  {
    title: "Pro Smartphone 256GB Titanium",
    sku: "PHN-PRO-256",
    category: "mobiles-tablets",
    price: 119900,
    compare: null,
    stock: 6,
    tax: 18,
    images: ["/images/promo/promo-01.png"],
    tags: "smartphone, flagship, pro, camera",
    short: "Flagship triple-camera phone in a titanium frame.",
    description:
      "Our top smartphone: titanium frame, triple-camera system with optical zoom, pro video modes and the fastest chip we stock.",
    specs: [["Display", "6.9 inch OLED, 120 Hz"], ["Camera", "Triple 48 MP"], ["Storage", "256 GB"], ["Warranty", "1 year"]],
  },
  {
    title: "10.9-inch Tablet 64GB",
    sku: "TAB-109-64",
    category: "mobiles-tablets",
    price: 54900,
    compare: 59900,
    stock: 18,
    tax: 18,
    images: [P(7), P(7, "bg-2")],
    tags: "tablet, ipad, drawing, study",
    short: "Slim tablet with a sharp display, great for study and play.",
    description:
      "A light, powerful tablet with a 10.9-inch Liquid Retina display, all-day battery and support for a stylus and keyboard. Ideal for note-taking, drawing and streaming.",
    specs: [["Display", "10.9 inch"], ["Storage", "64 GB"], ["Connectivity", "Wi-Fi 6, Bluetooth 5.2"], ["Battery", "Up to 10 hours"]],
  },
  {
    title: "Wired USB Gamepad Controller",
    sku: "GAM-PAD-USB",
    category: "gaming-audio",
    price: 1499,
    compare: 2499,
    stock: 60,
    tax: 18,
    images: [P(1), P(1, "bg-2")],
    tags: "gamepad, controller, pc gaming, usb",
    short: "Dual-vibration USB gamepad for PC and compatible consoles.",
    description:
      "Plug-and-play USB controller with dual vibration motors, a responsive D-pad and a non-slip grip. Works with Windows PCs and most emulators with no drivers needed.",
    specs: [["Connection", "USB, 1.8 m cable"], ["Compatibility", "Windows 11/10/8, Android (OTG)"], ["Vibration", "Dual motor"], ["Buttons", "12 + 2 analog sticks"]],
  },
  {
    title: "Studio Wireless Over-Ear Headphones",
    sku: "AUD-STUDIO-BL",
    category: "gaming-audio",
    price: 17999,
    compare: 21999,
    stock: 22,
    tax: 18,
    images: [P(9), P(9, "bg-2")],
    tags: "headphones, wireless, noise cancelling, audio",
    short: "Rich, balanced sound with active noise cancelling.",
    description:
      "Over-ear wireless headphones with adaptive noise cancelling, plush cushions and up to 20 hours of playback. Fold flat to slip into the included case.",
    specs: [["Playback", "Up to 20 hours"], ["Connectivity", "Bluetooth 5.0, 3.5 mm"], ["Noise cancelling", "Adaptive ANC"], ["Charging", "USB-C"]],
  },
  {
    title: "Gaming Headset with Mic",
    sku: "AUD-GAME-HS",
    category: "gaming-audio",
    price: 2499,
    compare: 3499,
    stock: 45,
    tax: 18,
    images: ["/images/countdown/countdown-01.png"],
    tags: "headset, gaming, microphone, audio",
    short: "Comfortable over-ear headset with a flexible noise-reducing mic.",
    description:
      "Padded leatherette ear cups, a flexible boom microphone and inline volume control. Plug it into a PC or console and start playing.",
    specs: [["Connection", "3.5 mm + USB power"], ["Microphone", "Flexible boom, noise-reducing"], ["Cable", "2.2 m"], ["Warranty", "6 months"]],
  },
  {
    title: "Portable Bluetooth Speaker",
    sku: "AUD-SPK-BT",
    category: "gaming-audio",
    price: 7999,
    compare: 9999,
    stock: 30,
    tax: 18,
    images: ["/images/countdown/speaker.png"],
    tags: "speaker, bluetooth, portable, waterproof",
    short: "Rugged, waterproof speaker with 360-degree sound.",
    description:
      "A tough, water-resistant portable speaker with powerful 360-degree sound and up to 12 hours of playtime. Pair two for stereo.",
    specs: [["Playtime", "Up to 12 hours"], ["Water resistance", "IP67"], ["Connectivity", "Bluetooth 5.0"], ["Charging", "USB-C"]],
  },
  {
    title: "Countertop Blender 1.5L",
    sku: "HOM-BLEND-15",
    category: "home-appliances",
    price: 3999,
    compare: 5499,
    stock: 35,
    tax: 18,
    images: [P(12), P(12, "bg-2")],
    tags: "blender, kitchen, smoothie, appliance",
    short: "Powerful 600W blender for smoothies, soups and sauces.",
    description:
      "A 1.5-litre shatter-resistant jar, stainless-steel blades and a simple dial for blending smoothies, soups and sauces in seconds. The jar and blades are dishwasher safe.",
    specs: [["Power", "600 W"], ["Capacity", "1.5 litre"], ["Speeds", "2 + pulse"], ["Warranty", "2 years"]],
  },
  {
    title: "Folding Motorised Treadmill",
    sku: "FIT-TREAD-F1",
    category: "health-fitness",
    price: 29990,
    compare: 34990,
    stock: 6,
    tax: 18,
    images: [P(11), P(11, "bg-2")],
    tags: "treadmill, fitness, cardio, home gym",
    short: "Foldable treadmill with a bright console and 12 programs.",
    description:
      "A compact motorised treadmill that folds away after your workout. Cushioned deck, 12 preset programs and a clear LCD console to track time, speed and calories.",
    specs: [["Motor", "2.0 HP"], ["Speed", "1 to 14 km/h"], ["Max user weight", "110 kg"], ["Folded size", "Stores upright"]],
  },
  {
    title: "Rugged Smartwatch with Alpine Band",
    sku: "WEA-RUGGED-49",
    category: "wearables",
    price: 74990,
    compare: 79990,
    stock: 0,
    tax: 18,
    images: [P(5), P(5, "bg-2")],
    tags: "smartwatch, wearable, fitness, outdoor",
    short: "Titanium smartwatch built for outdoor training.",
    description:
      "A tough titanium smartwatch with a bright always-on display, dual-frequency GPS, depth gauge and up to 36 hours of battery. Pick the band colour that suits you.",
    specs: [["Case", "49 mm titanium"], ["Battery", "Up to 36 hours"], ["Water resistance", "100 m"], ["Sensors", "GPS, heart rate, SpO2"]],
    variants: [
      { title: "Orange band", sku: "WEA-RUGGED-49-OR", price: 74990, stock: 7, attrs: { color: "Orange", image: P(5) } },
      { title: "Green band", sku: "WEA-RUGGED-49-GR", price: 74990, stock: 5, attrs: { color: "Green", image: P(5, "bg-2") } },
    ],
  },
];

module.exports = { categories, products };
